version: '3'
services:
  api_up:
    image: api_up
    container_name: up_api
    restart: always
    build:
      context: .
      dockerfile: API_UP/Dockerfile
    ports:
      - "5181:5181"
    volumes:
      - ./static:/var/opt/api_up/
